### ISSUE TITLE
MySQL 5.6 length limit on unique CharField prevents migration

### ISSUE THREAD

**Issue by leducvin** [qatrackplus/qatrackplus#602]
Hi, I think I am seeing symptoms of #32 and #138 still occuring. Specifically, I have:

```
Running migrations:
  Applying auth.0009_alter_user_last_name_max_length... OK (0.307s)
  Applying qa.0022_auto_20181120_1607... OK (0.260s)
  Applying qa.0023_set_recurrences... OK (0.544s)
  Applying qa.0024_remove_frequency_due_interval... OK (0.226s)
  Applying qa.0025_auto_20181129_1449... OK (0.557s)
  Applying qa.0026_copy_overdue_interval... OK (0.255s)
  Applying qa.0027_remove_frequency_overdue_interval... OK (0.200s)
  Applying qa.0028_auto_20181214_2209... OK (1.541s)
  Applying qa.0029_auto_20181217_0945... OK (0.091s)
  Applying qa.0030_auto_20190129_2156... OK (28.089s)
  Applying accounts.0001_initial... OK (0.325s)
  Applying accounts.0002_activedirectorygroupmap_defaultgroup...Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/opt/venv/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/venv/lib/python3.9/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/venv/lib/python3.9/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
```

Am upgrading v0.3.0.18 to v3.1.0 on MySQL 5.6.36

**Comment by leducvin** [comment]
I can confirm though that migrations completed successfully on MySQL 5.7 (which has higher limits than 5.6).

**Comment by randlet** [comment]
Right you are. I "fixed" this a while ago (https://github.com/qatrackplus/qatrackplus/commit/58f5973e8f13c745f59097f57c879402546ab880), but neglected to change the initial migration: https://github.com/qatrackplus/qatrackplus/blob/master/qatrack/accounts/migrations/0002_activedirectorygroupmap_defaultgroup.py#L21
