### ISSUE TITLE
Service Event adding new QA tests randomly

### ISSUE THREAD

**Issue by nsmela** [qatrackplus/qatrackplus#619]
Hi there,

We have a weird bug: when you open an existing service event for editing, it consistently doubles the queued QA, but with different tests.  For example, we have a service event with QA A02: Measure Voltage and B07: Measure Temp. When we open it to edit the service event, it has four tests: A02: Measure Voltage, B07: Measure Temp, A16: Couch accuracy and B16: Gantry Accuracy.

We can clear the excessive new tests and continue, but it's a bit of a hassle. It also appears to be only affecting a single service event. I can edit other service events just fine without new QA tests surprising us.

**Comment by nsmela** [comment]
I removed all qa tests from the service event, tried to save, got 500 internal server error:

```
[15/Jun/2022 11:17:36] ERROR [django.request:222] Internal Server Error: /servicelog/event/edit/107/
Traceback (most recent call last):
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\defaulttags.py", line 511, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\defaulttags.py", line 511, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\template\base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\forms\formsets.py", line 72, in __getitem__
    return self.forms[index]
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\forms\formsets.py", line 136, in forms
    for i in range(self.total_form_count())]
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\forms\formsets.py", line 110, in total_form_count
    return min(self.management_form.cleaned_data[TOTAL_FORM_COUNT], self.absolute_max)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\deployv31\venvs\qatrack31\lib\site-packages\django\forms\formsets.py", line 90, in management_form
    raise ValidationError(
django.core.exceptions.ValidationError: ['ManagementForm data is missing or has been tampered with']
```

**Comment by randlet** [comment]
Thanks @nsmela I've been able to isolate some code that looks related to this. I'm struggling to understand it but hopefully have it sorted out shortly.

**Comment by randlet** [comment]
Seems likely to be the same issue as issue #587

**Comment by nsmela** [comment]
Yes, sorry I didn't catch it. Anything I could do to help narrow-down the issue? Any files I could copy and forward to you?

**Comment by randlet** [comment]
I don't think I need any more info as I was able to track down the issue.  Just need to test everything a bit further. Thanks!
